### ISSUE TITLE
line 292 fails: govendor fetch github.com/anotheruser/repo

### ISSUE THREAD

**Issue by bertrandszoghy** [hlf-go/writing-chaincode#1]
Hello,

Could you clarify procedure to replace command on line 292 with a working one and explain better the purpose of the step? Right now am getting:

`[vagrant@centos7 mychaincode]$ govendor fetch github.com/anotheruser/repo
Username : 
Password :
# cd .; git clone https://github.com/anotheruser/repo /home/vagrant/gocode/.cache/govendor/github.com/anotheruser/repo
Cloning into '/home/vagrant/gocode/.cache/govendor/github.com/anotheruser/repo'...
remote: Repository not found.
fatal: repository 'https://github.com/anotheruser/repo/' not found
Error: failed to create repo "https://github.com/anotheruser/repo" in "/home/vagrant/gocode/.cache/govendor/github.com/anotheruser/repo" exit status 128
Failed to fetch package "github.com/anotheruser/repo"
github.com/kardianos/govendor/context.(*Context).Alter
        /home/vagrant/gocode/src/github.com/kardianos/govendor/context/modify.go:710
github.com/kardianos/govendor/run.(*runner).Modify
        /home/vagrant/gocode/src/github.com/kardianos/govendor/run/modify.go:152
github.com/kardianos/govendor/run.(*runner).run
        /home/vagrant/gocode/src/github.com/kardianos/govendor/run/run.go:98
github.com/kardianos/govendor/run.Run
        /home/vagrant/gocode/src/github.com/kardianos/govendor/run/run.go:44
main.main
        /home/vagrant/gocode/src/github.com/kardianos/govendor/main.go:35
runtime.main
        /usr/local/go/src/runtime/proc.go:185
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2197
[vagrant@centos7 mychaincode]$ echo $?
2
[vagrant@centos7 mychaincode]$ pwd
/home/vagrant/gocode/src/github.com/user/repo/mychaincode
[vagrant@centos7 mychaincode]$ echo $GOPATH
/home/vagrant/gocode
[vagrant@centos7 mychaincode]$ echo $PATH
/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/go/bin:/usr/local/go/bin:/home/vagrant/.local/bin:/home/vagrant/bin:/home/vagrant/gocode/bin
[vagrant@centos7 mychaincode]$
`

Thanks!

**Comment by paulwizviz** [comment]
`https://github.com/anotheruser/repo/` is only a hypothetical repository. If you wish to vendor this, it has to be an actual remote repo (e.g. github.com/hlf-go/fabrics) for the command `govendor fetch`.

Otherwise, as stated in later paragraph, you will need to use the `govendor add` command. Please refer to the [govendor documentation](https://github.com/kardianos/govendor) for full use case description.

More importantly, don't get too hung up with the `govendor` tool as you can just as well vendor using good old fashion `git clone` or numerous number of tools. The main thing is to ensure that you update the `vendor.json` accordingly.
